name: mobile_app_project
description: A mobile application built with Flutter and a Node.js backend.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - course_up/assets/images/
    - course_up/assets/
   